Background image set
KlaraGajaszek/CC2020Javascript pull request #15
Opened 2020-12-08 17:46 UTC by wojaneta

closes #4

2020-12-09 13:00 UTC, KlaraGajaszek requested changes

2020-12-09 13:00 UTC, KlaraGajaszek commented on src/styles/basics.scss
> +
Czy to jest nam tutaj potrzebne ?
Nie możemy zostawićczegoś takiego ?
    `body {
        background-image: url("../../static/assets/img/modes/background/QuizBackground.png");
        background-size: cover;
        background-repeat: no-repeat;
        margin: 0px;
        height: 100vh;
    }`

2020-12-09 18:16 UTC, wojaneta commented on src/styles/basics.scss
> +
też działa, dzięki :)

2020-12-09 19:55 UTC, maciekkwiet approved these changes

2020-12-10 10:44 UTC, KlaraGajaszek approved these changes

2020-12-10 17:12 UTC, merged