Question generator
KlaraGajaszek/CC2020Javascript pull request #32
Opened 2020-12-29 17:02 UTC by rafenoxu

closes #1

2021-01-02 18:12 UTC, maciekkwiet requested changes
Wygląda dobrze, ale @KlaraGajaszek czy to powinien być komponent nowy?
Według mnie ta logika powinna trafić chyba do głównego pliku App.js który będzie tym zarządzał, będzie on również renderował pytania, czy to nie powinno być również zrobione w tej PR?
Całość powinna być również podpięta i odpalana po kliknięciu przycisku PlayTheGame i chyba również w tej PR

2021-01-02 18:12 UTC, maciekkwiet commented on src/app/components/Question.js
> +      return -1;
Może spróbujmy to zapisać w jednej lini

2021-01-02 18:12 UTC, maciekkwiet commented on src/app/components/Question.js
> +    }
Wyżej korzystaliśmy z nr. Indeksu a nie nazwy więc bardzo możliwe ze będzie potrzebna nam dodatkowa funkcja konwertująca liczbe na nazwę bądź odwrotnie

2021-01-02 18:34 UTC, KlaraGajaszek commented on src/app/components/Question.js
> +  _getMaxId() {
Nie powinniśmy używać switch Case ze względu na wydajnosc i jakosc  kodu, tu jest ciekawy artykuł https://dev.to/lukyhenson/replace-your-switch-statement-and-multiple-if-and-else-using-object-literals-en-us-1dec. W tym projekcie na razie tak zostawmy bo nie skupiamy sie jeszcze na wydajności, ale tak na przyszłość

2021-01-02 18:42 UTC, KlaraGajaszek requested changes
Zgadzam się z Maćkiem fajnie by było tą logikę wynieść. Co chodzi o podpięcie  to zależy od Cb Rafał, jak chcesz to możemy przeniesć to na innego taska ? A co do logiki jeszcze im mniej mamy w środku tym lepiej.

2021-01-05 18:56 UTC, rafenoxu commented on src/app/components/Question.js
> +    }
Nie za bardzo rozumiem. Nazwy są przechowywane w tablicy i prawidłowa odpowiedź jest indeksem do tablicy + 1 więc chyba nie trzeba będzie nic zmieniać.

2021-01-07 20:34 UTC, merged