Picture display fixed and font in box changed
KlaraGajaszek/CC2020Javascript pull request #78
Opened 2021-01-16 18:28 UTC by wojaneta

closes #74 & font in box changed 
<img width="803" alt="Screenshot 2021-01-16 at 19 27 16" src="https://user-images.githubusercontent.com/63155419/104819877-f3fc3a00-5830-11eb-8b19-ede6bbac181f.png">

2021-01-17 01:12 UTC, maciekkwiet requested changes
Niestety będziemy musieli to jeszcze raz poprawić, może zróbmy max-width i height na auto, wtedy powinno to już wyglądać trochę lepiej ale przetestujmy to najpierw
![image](https://user-images.githubusercontent.com/33134609/104828394-48bba700-5869-11eb-9052-f0430f0efeb4.png)

2021-01-17 17:45 UTC, KlaraGajaszek requested changes
Jeszcze na mobilce się rozjeżdza 
![image](https://user-images.githubusercontent.com/59035908/104851244-363a7f80-58f4-11eb-8526-f8c0cb74298b.png)

2021-01-18 08:59 UTC, wojaneta commented
> Jeszcze na mobilce się rozjeżdza
> ![image](https://user-images.githubusercontent.com/59035908/104851244-363a7f80-58f4-11eb-8526-f8c0cb74298b.png)
> 1 . Spróbuj zrobić box-sizing na inherit powinno pomóc w problemie poniżej
> ![image](https://user-images.githubusercontent.com/59035908/104851393-0475e880-58f5-11eb-94d6-53990992527c.png)

box-sizing nie zadziałał, albo źle go ustawiałam :/ pokombinowałam jeszcze trochę i teraz wygląda to tak:
telefon:
<img width="234" alt="Screenshot 2021-01-18 at 09 53 03" src="https://user-images.githubusercontent.com/63155419/104893506-cd92e780-5973-11eb-9885-36f61379142c.png">
tablet:
<img width="322" alt="Screenshot 2021-01-18 at 09 53 17" src="https://user-images.githubusercontent.com/63155419/104893532-d683b900-5973-11eb-9ee5-2b393e915615.png">

2021-01-18 18:12 UTC, maciekkwiet approved these changes
Wydaje się okey, więc jak tez tak czujesz to mergujmy to :D

2021-01-18 19:19 UTC, merged